# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Vietlott' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Vietlott
  pod 'SwiftyJSON', '~> 3.1'
  pod 'ARSLineProgress', '~> 2.0'
  pod 'AFNetworking', '~> 3.0'
  pod 'Firebase'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  pod 'Firebase/Database'
  pod 'Kanna', '~> 2.0.0'

end
